apiVersion: v1
kind: ConfigMap
metadata: 
  name: vinti-config
data:
  APP_MODE: "production"
  WELCOME_MSG: "Hello Vinti"


#-----------------------------------------

apiVersion: v1
kind: secret
metadata:
  name: vinti-secret
type: Opaque
data:
  password: somepassword=====