# Kubernetes-specific YAML rules ðŸ§ 
# â€¢	metadata, spec, labels â†’ maps
#	â€¢	containers, env, ports, volumes â†’ lists
#	â€¢	Even one container must be inside a list
#	â€¢	Map (object) â†’ no dash
#	â€¢	List (array) â†’ dash required

#	â€¢	v1 â†’ Pod, Service, ConfigMap, Secret, Namespace, Node, PV, PVC 
#	â€¢	apps/v1 â†’ Deployment, StatefulSet, DaemonSet, ReplicaSet
#	â€¢	batch/v1 â†’ Job, CronJob
#	â€¢	networking.k8s.io/v1 â†’ Ingress, NetworkPolicy

apiVersion: apps/v1
kind: deployment
metedate:
  name: app_deployment
spec:
  replica: 2
  selector:
    matchLabels:
      app: FIS_app
  templete:
    metadata:
      labels: 
        app: FIS_app
    spec:
      containers:
        - name: app
          image: ngnix
          ports:
            - containerPort: 80